[[item]]
    code = "beer"
    rarity = "COMMON"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "STRENGTH"

    [item.locales.RU]
    name = "Пиво"
    consumeTemplate = [
        "Кружка пива для нашего постоянного гостя <b>${personage_badge_with_name}</b>",
        "Нет ничего лучше кружки прохладного пива после тяжёлого дня. Верно, <b>${personage_badge_with_name}</b>?",
        "Пивка! Для рывка!",
        "Губит людей не пиво. Губит людей вода!"
    ]

    [item.locales.EN]
    name = "Beer"
    consumeTemplate = [
        "A beer mug for our regular guest <b>${personage_badge_with_name}</b>",
        "There is nothing better than a mug of cool beer after a hard day. Right, <b>${personage_badge_with_name}</b>?"
    ]

    [item.locales.ES]
    name = "Cerveza"
    consumeTemplate = [
        "¡Una jarra de cerveza para nuestro cliente habitual <b>${personage_badge_with_name}</b>!",
        "No hay nada mejor que una jarra de cerveza bien fría tras un día duro. ¿Verdad, <b>${personage_badge_with_name}</b>?",
        "¡Una cervecita para el tirón!",
        "Lo que arruina a la gente no es la cerveza... ¡es el agua!"
    ]

[[item]]
    code = "slime_nastoyka"
    rarity = "RARE"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "ATTACK"

    [item.locales.RU]
    name = "Настойка на слаймах"
    consumeTemplate = [
        "Я смотрю, <b>${personage_badge_with_name}</b> знает толк в качественной выпивке! И слаймах.",
        "Настойка на слаймах, пойманных в окрестностях Крезара. Утром даже голова не болит! Но от других побочек никто не застрахован..."
    ]

    [item.locales.EN]
    name = "Tincture on slimes"
    consumeTemplate = [
        "I see <b>${personage_badge_with_name}</b> knows a lot about quality booze! And slime.",
        "Tincture on slimes caught in the vicinity of Krezar. It's not even a headache in the morning! But no one is immune from other side effects..."
    ]

    [item.locales.ES]
    name = "Licor de slime"
    consumeTemplate = [
        "Veo que <b>${personage_badge_with_name}</b> sabe de buen trago... ¡y de slimes también!",
        "Licor preparado con slimes cazados en los alrededores de Krezar. ¡Ni resaca al día siguiente! Aunque... de otros efectos no se salva nadie."
    ]

[[item]]
    code = "grechka_tea"
    rarity = "COMMON"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "AGILITY"

    [item.locales.RU]
    name = "Гречкин чай"
    consumeTemplate = [
        "Нет не из гречихи, да на гречке, угощайтесь, <b>${personage_badge_with_name}</b>.",
        "Теплый напиток со вкусом обеда - готов!"
    ]

    [item.locales.EN]
    name = "Buckwheat tea"
    consumeTemplate = [
        "Fresh buckwheat, treat yourself, <b>${personage_badge_with_name}</b>.",
        "A warm drink with the taste of lunch is ready!"
    ]

    [item.locales.ES]
    name = "Té de chícharo"
    consumeTemplate = [
        "No es de chícharo, pero sí con él. Disfruta, <b>${personage_badge_with_name}</b>.",
        "¡Bebida calentita con sabor a almuerzo, lista!"
    ]

[[item]]
    code = "monastery_wine"
    rarity = "UNCOMMON"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "WISDOM"

    [item.locales.RU]
    name = "Монастырское вино"
    consumeTemplate = [
        "Ароматный букет ладана и масла защищает душу и тело от происков врагов.",
        "Вино категорически запрещено в употребление демонам и нежити. Но тебе же нечего бояться, правда?"
    ]

    [item.locales.EN]
    name = "Monastery wine"
    consumeTemplate = [
        "A fragrant bouquet of incense and oil protects the soul and body from the machinations of enemies.",
        "Wine is strictly forbidden for use by demons and undead. But you have nothing to be afraid of, right?"
    ]

    [item.locales.ES]
    name = "Vino monástico"
    consumeTemplate = [
        "Un bouquet fragante de incienso y aceite protege el alma y el cuerpo de las maquinaciones del enemigo.",
        "El consumo de este vino está estrictamente prohibido para demonios y no muertos. Pero tú no tienes nada que temer, ¿verdad?"
    ]

[[item]]
    code = "gorgon"
    rarity = "UNCOMMON"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "ATTACK"

    [item.locales.RU]
    name = "Горгоний соблазн"
    consumeTemplate = [
        "Настойка на змеином яде, ее можно не только пить, но и втирать в колени!",
        "Таверна не несёт ответственности в случае частичного превращения в камень. За твоё здоровье!"
    ]

    [item.locales.EN]
    name = "Gorgon temptation"
    consumeTemplate = [
        "Tincture of snake venom, you can not only drink it, but also rub it into your knees!",
        "The tavern is not responsible in case of partial transformation into stone. To your health!"
    ]

    [item.locales.ES]
    name = "Tentación gorgónica"
    consumeTemplate = [
        "Tintura de veneno de serpiente: ¡puedes beberla o frotártela en las rodillas!",
        "La taberna no se hace responsable si quedas hecho parcialmente una piedra. ¡Salud!"
    ]

[[item]]
    code = "cat_soup"
    rarity = "UNCOMMON"
    isAvailable = true
    category = "MAIN_DISH"
    effectCharacteristic = "HEALTH"

    [item.locales.RU]
    name = "Суп с котом"
    consumeTemplate = [
        "Суп с котом для <b>${personage_badge_with_name}</b>! Мяукал ещё 15 минут назад"
    ]

    [item.locales.EN]
    name = "Cat soup"
    consumeTemplate = [
        "Cat soup for <b>${personage_badge_with_name}</b>! Meowed 15 minutes ago"
    ]

    [item.locales.ES]
    name = "Sopa de gato"
    consumeTemplate = [
        "¡Sopa de gato para <b>${personage_badge_with_name}</b>! Maullaba hace apenas 15 minutos"
    ]

[[item]]
    code = "roast_maggoose"
    rarity = "RARE"
    isAvailable = true
    category = "MAIN_DISH"
    effectCharacteristic = "WISDOM"

    [item.locales.RU]
    name = "Жаркое из маггуся"
    consumeTemplate = [ "Жаркое из свежего маггуся! Повышает магическую потенцию" ]

    [item.locales.EN]
    name = "Roast of maggoose"
    consumeTemplate = [ "Roast of fresh maggoose! Increases magical potency" ]

    [item.locales.ES]
    name = "Asado de magganso"
    consumeTemplate = [ "¡Asado de magganso fresco! Aumenta la potencia mágica" ]

[[item]]
    code = "fried_potato"
    rarity = "COMMON"
    isAvailable = true
    category = "MAIN_DISH"
    effectCharacteristic = "HEALTH"

    [item.locales.RU]
    name = "Жареная картошечка"
    consumeTemplate = [
        "Мммм, горячая картошечка... Отжарили ее для <b>${personage_badge_with_name}</b>!",
        "Горячее этой картошечки - только ты!"
    ]

    [item.locales.EN]
    name = "Fried potatoes"
    consumeTemplate = [ "Only you are hotter than this potato!" ]

    [item.locales.ES]
    name = "Papas fritas"
    consumeTemplate = [
        "Mmm... papitas bien calientes... ¡recién fritas para <b>${personage_badge_with_name}</b>!",
        "¡Solo tú estás más caliente que estas papas!"
    ]

[[item]]
    code = "olivier"
    rarity = "RARE"
    isAvailable = false
    category = "MAIN_DISH"
    effectCharacteristic = "HEALTH"

    [item.locales.RU]
    name = "Оливье"
    consumeTemplate = [
        "Домашний салатик, приготовленный с любовью!",
        "<b>${personage_badge_with_name}</b>, куда делся тазик оливье?",
        "Такой салат ещё вкуснее рядом с хорошими товарищими. Хорошо, что <b>${personage_badge_with_name}</b> один из них!",
    ]

    [item.locales.ES]
    name = "Ensaladilla rusa"
    consumeTemplate = [
        "¡Una ensaladita casera hecha con amor!",
        "<b>${personage_badge_with_name}</b>, ¿a dónde se fue el cubo de ensaladilla?",
        "Esta ensalada sabe aún mejor junto a buenos amigos. ¡Qué suerte que <b>${personage_badge_with_name}</b> sea uno de ellos!"
    ]

[[item]]
    code = "champagne"
    rarity = "RARE"
    isAvailable = false
    category = "DRINK"
    effectCharacteristic = "WISDOM"

    [item.locales.RU]
    name = "Шампанское"
    consumeTemplate = [
        "Звон бокалов ласкает слух!",
        "С Новым Годом, <b>${personage_badge_with_name}</b>!",
        "С каждым глотком настроение становится более праздничным! Поделись им с друзьями",
        "Праздник к нам приходит, праздник к нам приходит! А вместе с ним и пьяный <b>${personage_badge_with_name}</b>!",
        "Счастья! Здоровья! Что б меч стоял, и деньги были!"
    ]

    [item.locales.ES]
    name = "Champán"
    consumeTemplate = [
        "¡El tintinear de las copas alegra el alma!",
        "¡Feliz Año Nuevo, <b>${personage_badge_with_name}</b>!",
        "¡Con cada sorbo, el ánimo se vuelve más festivo! Compártelo con tus amigos",
        "¡La fiesta ya llegó, la fiesta ya llegó! ¡Y con ella, <b>${personage_badge_with_name}</b> bien borracho!",
        "¡Salud! ¡Dinero! ¡Y que no falte espada ni fortuna!"
    ]

[[item]]
    code = "gluhwein"
    rarity = "RARE"
    isAvailable = false
    category = "DRINK"
    effectCharacteristic = "ATTACK"

    [item.locales.RU]
    name = "Глинтвейн"
    consumeTemplate = [
        "Согревает душу и тело <b>${personage_badge_with_name}</b>!",
        "Лучшее вино, свежие апельсины и секретные специи пострадали, чтобы оказаться в стакане <b>${personage_badge_with_name}</b>.",
        "Отличный напиток для этой холодной погоды!",
        "Год был не простым... Но <b>${personage_badge_with_name}</b> был на высоте!",
    ]
    
    [item.locales.ES]
    name = "Vino caliente"
    consumeTemplate = [
        "¡Calienta el alma y el cuerpo de <b>${personage_badge_with_name}</b>!",
        "El mejor vino, naranjas frescas y especias secretas sufrieron para terminar en el vaso de <b>${personage_badge_with_name}</b>.",
        "¡Una bebida perfecta para este clima frío!",
        "Este año no fue fácil... ¡Pero <b>${personage_badge_with_name}</b> estuvo a la altura!"
    ]

[[item]]
    code = "pumpkin_nastoyka"
    rarity = "RARE"
    isAvailable = false
    category = "DRINK"
    effectCharacteristic = "ATTACK"

    [item.locales.RU]
    name = "Тыквенная настойка"
    consumeTemplate = [
        "Осенняя тыква, настоянная на крепком духе! Для <b>${personage_badge_with_name}</b>!",
        "Говорят, что после этой настойки начинаешь видеть духов. Или дело в <b>${personage_badge_with_name}</b>?",
        "Рецепт передаётся из поколения в поколение. <b>${personage_badge_with_name}</b> определённо оценит вкус осени!",
        "Сладкая тыква и жгучий спирт - идеальное сочетание для храбрых искателей вроде <b>${personage_badge_with_name}</b>!"
    ]

[[item]]
    code = "pumpkin_soup"
    rarity = "RARE"
    isAvailable = false
    category = "MAIN_DISH"
    effectCharacteristic = "HEALTH"

    [item.locales.RU]
    name = "Тыквенный суп"
    consumeTemplate = [
        "Горячий тыквенный суп согреет <b>${personage_badge_with_name}</b> в холодную осеннюю ночь!",
        "Суп из отборных тыкв, выращенных на кладбище... Шутка! Или нет, <b>${personage_badge_with_name}</b>?",
        "Сливочный, ароматный, целебный! Именно то, что нужно <b>${personage_badge_with_name}</b> перед битвой!",
        "Бабушкин рецепт с секретным ингредиентом. <b>${personage_badge_with_name}</b> чувствует прилив сил!"
    ]
