welcomeGroup = """\
Welcome to the tavern of the city of Krezar, Seekers! \
Sit down at the table, order a drink, make yourself at home
"""
chooseLanguage = "Choose language:"
onlyAdminAction = "This action is available only for administrators"
internalError = "Unexpected error, try again later"

hoursShort = "hh"
minutesShort = "mm"

#Ñ‚ĞµĞºÑÑ‚Ğ° Ğ´Ğ»Ñ Ğ³Ñ€ÑƒĞ¿Ğ¿Ñ‹
groupStats = """\
ğŸ“Š<b>Group statistics:</b>

ğŸ—¡Successful raids: ${raids_count}
ğŸ¤ºCompleted duels: ${duels_count}

ğŸ»Spent at the tavern: ${money_icon}${tavern_money_spent}
"""

# Ñ‚ĞµĞºÑÑ‚Ğ° Ğ´Ğ»Ñ Ğ»Ğ¸Ñ‡ĞºĞ¸
# TODO Ğ¿ĞµÑ€ĞµĞ½ĞµÑÑ‚Ğ¸ ĞºÑƒĞ´Ğ°-Ğ½Ğ¸Ğ±ÑƒĞ´ÑŒ
receptionDesk = "Hello! How can I help you?"
