chooseLanguage = "Choose language:"
onlyAdminAction = "This action is available only for administrators"
internalError = "Unexpected error, try again later"

hoursShort = "hh"
minutesShort = "mm"

contrabandEffect = "\n<code>-ðŸ“¦Contraband: ${effect} ${time_icon}${duration}</code>"