welcomeGroup = """\
Welcome to the tavern of the city of Krezar, Seekers! \
Sit down at the table, order a drink, make yourself at home
"""
chooseLanguage = "Choose language:"
onlyAdminLanguage = "This action is available only for administrators"
internalError = "Unexpected error, try again later"
profileTemplate = """\
${personage_icon}${personage_name}
${money_icon}Gold: ${personage_money}
${energy_icon}Energy: ${energy_value}%"""

#—Ç–µ–∫—Å—Ç–∞ –¥–ª—è –≥—Ä—É–ø–ø—ã
groupStats = """\
üìä<b>Group statistics:</b>

üó°Successful raids: ${raids_count}
ü§∫Completed duels: ${duels_count}

üçªSpent at the tavern: ${money_icon}${tavern_money_spent}
"""

# —Ç–µ–∫—Å—Ç–∞ –¥–ª—è –ª–∏—á–∫–∏
# TODO –ø–µ—Ä–µ–Ω–µ—Å—Ç–∏ –∫—É–¥–∞-–Ω–∏–±—É–¥—å
welcomeUser = "Welcome to the tavern, Seeker!"
receptionDesk = "Hello! How can I help you?"
mainMenu = [
    "Make yourself comfortable, take your time"
]
