joinRaidEvent = "Join raidðŸ—¡"
raidStartsPrefix = "The battle will begin in"
hoursShort = "h"
minutesShort = "m"
successJoinEvent = "You have successfully joined the event!"
userAlreadyInThisEvent = "You are already participating in this event!"
userAlreadyInOtherEvent = "You are already participating in another event!"
expiredRaid = "This event is over!"
successRaid = [
    "Raid was successful."
]
failureRaid = [
    "The seekers failed the raid."
]
