joinRaidEvent = "Join raidğŸ—¡(${energy_icon}${energy_cost}%)"
userAlreadyInOtherEvent = "âŒYou are already participating in another event!"
expiredRaid = "âŒThis event is over!"
successRaid = [
    "Raid was successful."
]
failureRaid = [
    "The seekers failed the raid."
]
