chooseLanguage = "–¢—ñ–ª–¥—ñ —Ç–∞“£–¥–∞“£—ã–∑:"
onlyAdminAction = "–ë“±–ª ”ô—Ä–µ–∫–µ—Ç —Ç–µ–∫ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä–ª–∞—Ä“ì–∞ “ì–∞–Ω–∞ “õ–æ–ª–∂–µ—Ç—ñ–º–¥—ñ"
internalError = "“ö–∞—Ç–µ, –∫–µ–π—ñ–Ω—ñ—Ä–µ–∫ “õ–∞–π—Ç–∞–ª–∞–ø –∫”©—Ä—ñ“£—ñ–∑"

hoursShort = "—Å–∞“ì."
minutesShort = "–º–∏–Ω."

# —Ç–µ–∫—Å—Ç–∞ –¥–ª—è –ª–∏—á–∫–∏
receptionDesk = "–°”ô–ª–µ–º–µ—Ç—Å—ñ–∑ –±–µ! –ö”©–º–µ–≥—ñ–º “õ–∞–∂–µ—Ç –ø–µ?"

contrabandEffect = "\n<code>-üì¶–ö–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥–∞: ${effect} ${time_icon}${duration}</code>"
