welcomeGroup = """\
–ö—Ä–µ—Å–∞—Ä “õ–∞–ª–∞—Å—ã–Ω–¥–∞“ì—ã —Ç–∞–≤–µ—Ä–Ω–∞“ì–∞ “õ–æ—à –∫–µ–ª–¥—ñ“£—ñ–∑–¥–µ—Ä, –Ü–∑–¥–µ—É—à—ñ–ª–µ—Ä! \
–ñ–∞–π“ì–∞—Å—ã“£—ã–∑–¥–∞—Ä, —Å—É—Å—ã–Ω —Ç–∞–ø—Å—ã—Ä—ã—Å –±–µ—Ä—ñ“£—ñ–∑–¥–µ—Ä, ”©–∑–¥–µ—Ä—ñ“£—ñ–∑–¥—ñ “Ø–π–¥–µ–≥—ñ–¥–µ–π —Å–µ–∑—ñ–Ω—ñ“£—ñ–∑–¥–µ—Ä
"""
chooseLanguage = "–¢—ñ–ª–¥—ñ —Ç–∞“£–¥–∞“£—ã–∑:"
onlyAdminLanguage = "–ë“±–ª ”ô—Ä–µ–∫–µ—Ç —Ç–µ–∫ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä–ª–∞—Ä“ì–∞ “ì–∞–Ω–∞ “õ–æ–ª–∂–µ—Ç—ñ–º–¥—ñ"
internalError = "“ö–∞—Ç–µ, –∫–µ–π—ñ–Ω—ñ—Ä–µ–∫ “õ–∞–π—Ç–∞–ª–∞–ø –∫”©—Ä—ñ“£—ñ–∑"

# —Ç–µ–∫—Å—Ç–∞ –¥–ª—è –≥—Ä—É–ø–ø—ã
groupStats = """\
üìä<b>–ì—Ä—É–ø–ø–∞–Ω—ã“£ —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞—Å—ã:</b>

üó°–°”ô—Ç—Ç—ñ —Ä–µ–π–¥—Ç–µ—Ä: ${raids_count}
ü§∫–ê—è“õ—Ç–∞–ª“ì–∞–Ω –¥—É—ç–ª—å–¥–µ—Ä: ${duels_count}

üçª–¢–∞–≤–µ—Ä–Ω–∞–¥–∞ –∂“±–º—Å–∞–ª–¥—ã: ${money_icon}${tavern_money_spent}
"""
personageGroupStats = """\
üìä<b>–°—ñ–∑–¥—ñ“£ –≥—Ä—É–ø–ø–∞–¥–∞“ì—ã —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞“£—ã–∑:</b>

üó°–°”ô—Ç—Ç—ñ —Ä–µ–π–¥—Ç–µ—Ä: ${raids_success}/${raids_total}
ü§∫–ñ–µ“£–≥–µ–Ω –¥—É—ç–ª—å–¥–µ—Ä: ${duels_wins}/${duels_total}

üçª–¢–∞–≤–µ—Ä–Ω–∞–¥–∞ –∂“±–º—Å–∞–ª–¥—ã: ${money_icon}${tavern_money_spent}
‚öí–ë“Ø–≥—ñ–Ω–≥—ñ –∫“Ø–Ω–Ω—ñ“£ “Ø–∑–¥—ñ–∫ –∂“±–º—ã—Å–∫–µ—Ä—ñ: ${spin_wins_count}
"""

# —Ç–µ–∫—Å—Ç–∞ –¥–ª—è –ª–∏—á–∫–∏
welcomeUser = "–¢–∞–≤–µ—Ä–Ω–∞“ì–∞ “õ–æ—à –∫–µ–ª–¥—ñ“£—ñ–∑, –Ü–∑–¥–µ—É—à—ñ!"
receptionDesk = "–°”ô–ª–µ–º–µ—Ç—Å—ñ–∑ –±–µ! –ö”©–º–µ–≥—ñ–º “õ–∞–∂–µ—Ç –ø–µ?"
mainMenu = [
    "–ñ–∞–π“ì–∞—Å—ã“£—ã–∑, –∞—Å—ã“õ–ø–∞“£—ã–∑"
]
