duelMustContainsMention = """\
    –î—É—ç–ª—å–≥–µ “õ–∞—Ä—Å—ã–ª–∞—Å—Ç—ã —Ç–∞“£–¥–∞“£—ã–∑! –î—É—ç–ª—å –±–∞—Å“õ–∞ –ø–∞–π–¥–∞–ª–∞–Ω—É—à—ã–Ω—ã“£ —Ö–∞–±–∞—Ä–ª–∞–º–∞—Å—ã–Ω–∞ –∂–∞—É–∞–ø –∂–∞–∑—ã–ø \
    –Ω–µ–º–µ—Å–µ —Ö–∞–±–∞—Ä–ª–∞–º–∞–¥–∞ –æ–Ω—ã –∞—Ç–∞–ø ”©—Ç—ñ“£—ñ–∑, –º—ã—Å–∞–ª—ã: <code>${duel_command} @user</code>.
    """
duelWithDifferentBot = [
    "“ö–∞—Ä—Å—ã–ª–∞—Å —Ä–µ—Ç—ñ–Ω–¥–µ –∂–∞–Ω—ã –±–∞—Ä –±—ñ—Ä–µ—É–¥—ñ —Ç–∞“£–¥–∞“£—ã–∑!"
]
duelWithThisBot = [
    "–ú–µ–Ω —Å—ñ–∑–≥–µ “õ—ã–∑–º–µ—Ç–∫–µ—Ä–ª–µ—Ä–º–µ–Ω “±—Ä—ã—Å–ø–∞—É–¥—ã “±—Å—ã–Ω–∞–º—ã–Ω! ”ò–π—Ç–ø–µ—Å–µ, —Å—ñ–∑–¥—ñ“£ —Å—ã—Ä–∞“£—ã–∑ –¥–∞—è—à—ã–¥–∞–Ω –∞—Ä–Ω–∞–π—ã –∫”©–±—ñ–∫–ø–µ–Ω –∞—è“õ—Ç–∞–ª—É—ã –º“Ø–º–∫—ñ–Ω."
]
duelWithYourself = "–°—ñ–∑ ”©–∑-”©–∑—ñ“£—ñ–∑–±–µ–Ω –¥—É—ç–ª—å –∂–∞—Å–∞–π –∞–ª–º–∞–π—Å—ã–∑!"
duelWithInitiatorNotEnoughMoney = [
    "–¢–æ“õ—Ç–∞–π —Ç“±—Ä—ã–Ω—ã–∑! –ê—Ä–µ–Ω–∞–Ω—ã –ø–∞–π–¥–∞–ª–∞–Ω—É “Ø—à—ñ–Ω —Å—ñ–∑–≥–µ –∫–µ–º –¥–µ–≥–µ–Ω–¥–µ ${money_icon}${money_count} “õ–∞–∂–µ—Ç. –ê–ª–¥—ã–º–µ–Ω –±–∞—Ä—ã–ø, –∂“±–º—ã—Å —ñ—Å—Ç–µ“£—ñ–∑",
    "–ê—Ä–µ–Ω–∞“ì–∞ –∫—ñ—Ä—É “õ“±–Ω—ã ${money_icon}${money_count}, –±—ñ—Ä—ñ–Ω—à—ñ–¥–µ–Ω, –∂“±–º—ã—Å —ñ—Å—Ç–µ–ø –∫–µ–ª!",
    "–ñ–µ–∫–ø–µ-–∂–µ–∫ - –∫–µ–¥–µ–π–ª–µ—Ä–¥—ñ“£ –µ–º–µ—Å, –±–∞–π–ª–∞—Ä–¥—ã“£ –∞—Ä—Ç—ã“õ—à—ã–ª—ã“ì—ã. ${money_icon}${money_count} —Ç–∞–ø—Å–∞–Ω “õ–∞–Ω–∞ –∫–∞–π—Ç—ã–ø –∫–µ–ª.",
    "–ë“±–ª –∂–µ–∫–ø–µ-–∂–µ–∫—Ç—ñ –∫”©—Ç–µ—Ä–µ –∞–ª–º–∞–π—Ç—ã–Ω —Å–∏—è“õ—Ç—ã—Å—ã“£! ${money_icon}${money_count} —Ç–∞–±—É—ã“£ –∫–µ—Ä–µ–∫."
]
personageAlreadyStartDuel = "–°—ñ–∑ –±–∞—Å“õ–∞ –¥—É—ç–ª—å–¥—ñ –±–∞—Å—Ç–∞–¥—ã“£—ã–∑! –û–Ω—ã“£ –∞—è“õ—Ç–∞–ª—É—ã–Ω –∫“Ø—Ç—ñ“£—ñ–∑."
notDuelAcceptingPersonage = "–î—É—ç–ª—å–≥–µ —Å—ñ–∑–¥—ñ —à–∞“õ—ã—Ä“ì–∞–Ω –∂–æ“õ!"
expiredDuel = [
    "–î—É—ç–ª—å–≥–µ —à–∞“õ—ã—Ä—É –µ–ª–µ–Ω–±–µ–¥—ñ",
    "${mention_acceptor_icon_with_name}: –ú–µ–Ω –¥—É—ç–ª—å–≥–µ –±–∞—Ä“ì—ã–º –∫–µ–ª–µ–¥—ñ –º–µ, –∫–µ–ª–º–µ–π–¥—ñ –º–µ, –º–∞“ì–∞–Ω –±”ô—Ä—ñ–±—ñ—Ä!",
    "${mention_acceptor_icon_with_name} –¥—É—ç–ª—å–≥–µ —à—ã“ì–∞ –∞–ª–º–∞–π–¥—ã. –ö–µ–π—ñ–Ω—ñ—Ä–µ–∫ “õ–æ“£—ã—Ä–∞—É —à–∞–ª—ã“£—ã–∑.",
]
declinedDuel = [
    "“ö–∞–±—ã–ª–¥–∞—É—à—ã —Ç–∞—Ä–∞–ø —à–∞“õ—ã—Ä—É–¥—ã “õ–∞–±—ã–ª–¥–∞–º–∞–¥—ã!",
    "–•–∞! ${mention_initiator_icon_with_name}, –¥—É—ç–ª—å–≥–µ —à–∞“õ—ã—Ä—É“ì–∞ –∞“õ—ã–º–∞“õ—Ç—ã –±–∞—Å“õ–∞ –∂–µ—Ä–¥–µ–Ω —ñ–∑–¥–µ!"
]
finishedDuel = [
    """\
–Ü–∑–¥–µ—É—à—ñ ${mention_winner_icon_with_name} –∂–µ“£—ñ–ø \
${mention_loser_icon_with_name}-–Ω—ñ“£ —Ç–∞—Å-—Ç–∞–ª“õ–∞–Ω—ã–Ω —à—ã“ì–∞—Ä–¥—ã""",
    "${mention_loser_icon_with_name} –∂–µ“£—ñ–ª—ñ—Å–∫–µ “±—à—ã—Ä–∞–¥—ã",
]
acceptDuelButton = "“ö–∞–±—ã–ª –∞–ª—Éüó°"
declineDuelButton = "–ë–∞—Å —Ç–∞—Ä—Ç—Éüëê"
duelWithUnknownUser = [
    """\
”®–∫—ñ–Ω—ñ—à–∫–µ –æ—Ä–∞–π, “õ—ã–∑–º–µ—Ç–∫–µ—Ä–ª–µ—Ä –∂–µ–∫–ø–µ-–∂–µ–∫–∫–µ –∫—ñ–º–¥—ñ —à–∞“õ—ã—Ä“ì–∞–Ω—ã“£—ã–∑–¥—ã –±—ñ–ª–º–µ–π–¥—ñ.\
–ú“Ø–º–∫—ñ–Ω —Å—ñ–∑–¥—ñ“£ –¥–æ—Å—ã“£—ã–∑ –±“±–ª —Ç–∞–≤–µ—Ä–Ω–∞“ì–∞ ”ô–ª—ñ –∫–µ–ª–º–µ–≥–µ–Ω –Ω–µ–º–µ—Å–µ –æ–ª –∞—Ç—ã–Ω ”©–∑–≥–µ—Ä—Ç–∫–µ–Ω —à—ã“ì–∞—Ä."""
]
duelIsLocked = "–î—É—ç–ª—å ”©“£–¥–µ–ª—É–¥–µ, –∫–µ–π—ñ–Ω—ñ—Ä–µ–∫ “õ–∞–π—Ç–∞–ª–∞–ø –∫”©—Ä—ñ“£—ñ–∑."
personageDuelResult = "${personage_badge_with_name}: ${damage_dealt}üí• ${damage_taken}üõ° ${dodges_count}üí®"
duelAlreadyFinished = "–î—É—ç–ª—å –µ—Ä—Ç–µ—Ä–µ–∫ –∞—è“õ—Ç–∞–ª–¥—ã, –±—ñ—Ä–∞“õ –∂“Ø–π–µ–ª—ñ–∫ “õ–∞—Ç–µ–≥–µ –±–∞–π–ª–∞–Ω—ã—Å—Ç—ã –Ω”ô—Ç–∏–∂–µ –∫”©—Ä—Å–µ—Ç—ñ–ª–º–µ–¥—ñ. –ö–µ—à—ñ—Ä—ñ–º —Å“±—Ä–∞–π–º—ã–∑."
