[menu]
profileButton = "üë§–ü—Ä–æ—Ñ–∏–ª—å"
languageButton = "üåê–¢—ñ–ª"
receptionDeskButton = "‚úçÔ∏è“ö–∞–±—ã–ª–¥–∞—É"
backButton = "‚¨ÖÔ∏è–ê—Ä—Ç“õ–∞"
resetCharacteristicsButton = "üìñ“∞–º—ã—Ç—É –∫—ñ—Ç–∞–±—ã"
changeNameButton = "üîÆ–ê—Ç—ã–º–¥—ã ”©–∑–≥–µ—Ä—Ç—É"

[changeName]
changeNameWithoutName="–ê—Ç—ã“£—ã–∑ –±–æ—Å –±–æ–ª–º–∞—É—ã –∫–µ—Ä–µ–∫!"
cancelChangeName = "–°–∏“õ—ã—Ä–ª—ã —à–µ“£–±–µ—Ä ”©—à—ñ–ø –±–∞—Ä–∞ –∂–∞—Ç—ã—Ä. –ö–µ–ª–µ—Å—ñ –∂–æ–ª—ã..."
confirmName = "–°—ñ–∑–¥—ñ“£ –∂–∞“£–∞ –∞—Ç—ã“£—ã–∑: <code>${name}</code>. –î“±—Ä—ã—Å –ø–∞?"
personageNameInvalidLength = """\
–ö–µ—à—ñ—Ä—ñ“£—ñ–∑, –±—ñ—Ä–∞“õ —Å–∏“õ—ã—Ä–ª—ã —à–µ“£–±–µ—Ä–¥—ñ“£ –∞—Ç–∞—É—ã–Ω–¥–∞ —Ç–∞“£–±–∞–ª–∞—Ä —à–µ–≥—ñ –±–∞—Ä. ${min_name_length} - ${max_name_length} —Ç–∞“£–±–∞"""
personageNameInvalidSymbols = """\
”®–∫—ñ–Ω—ñ—à–∫–µ –æ—Ä–∞–π, —Å–∏“õ—ã—Ä–ª—ã —à–µ“£–±–µ—Ä–¥–µ –∞—Ç—ã“£—ã–∑–¥—ã —Å–∞“õ—Ç–∞—É —É—à—ñ–Ω —Å—ñ–∑ —Ç–µ–∫ –º—ã–Ω–∞–ª–∞—Ä–¥—ã –ø–∞–π–¥–∞–ª–∞–Ω–∞ –∞–ª–∞—Å—ã–∑: \
<code>–ö–∏—Ä–∏–ª–ª, –ª–∞—Ç—ã–Ω, —Å–∞–Ω–¥–∞—Ä, —Ç–∞“£–±–∞–ª–∞—Ä _-.#‚Ññ –∂”ô–Ω–µ –ø—Ä–æ–±–µ–ª</code>"""
successNameChange = "–ê—Ç—ã“£—ã–∑ —Å”ô—Ç—Ç—ñ ”©–∑–≥–µ—Ä—Ç—ñ–ª–¥—ñ! –°–∏“õ—ã—Ä–ª—ã —à–µ“£–±–µ—Ä ”©—à—ñ–ø –±–∞—Ä–∞ –∂–∞—Ç—ã—Ä."
internalError = "–°–∏“õ—ã—Ä–ª—ã —à–µ“£–±–µ—Ä –∂—ã–ø—ã–ª—ã“õ—Ç–∞–π –±–∞—Å—Ç–∞–ø, –∫–µ–Ω–µ—Ç—Ç–µ–Ω —Å”©–Ω—ñ–ø “õ–∞–ª–¥—ã. –ë—ñ—Ä –∂–µ—Ä–¥–µ “õ–∞—Ç–µ —à—ã“õ“õ–∞–Ω —Å–∏—è“õ—Ç—ã, ”ô—Ä–µ–∫–µ—Ç—Ç—ñ –∫–µ–π—ñ–Ω—ñ—Ä–µ–∫ “õ–∞–π—Ç–∞–ª–∞“£—ã–∑."
cancelButton = "‚ùå–ë–∞—Å —Ç–∞—Ä—Ç—É"
confirmButton = "‚úÖ–ë–∞—Ä–ª—ã“ì—ã –¥“±—Ä—ã—Å"
repeatButton = "üîÑ–¢–∞“ì—ã –±—ñ—Ä —Ä–µ—Ç"

[characteristics]
resetConfirmation = """\
“∞–º—ã—Ç—É –∫—ñ—Ç–∞–±—ã–Ω –æ“õ—É “Ø—à—ñ–Ω —Å—ñ–∑ ${money_icon}${money_count} —Ç”©–ª–µ—É –∫–µ—Ä–µ–∫c—ñ–∑. \
–ï—Å–∫—ñ –¥–∞“ì–¥—ã–ª–∞—Ä—ã“£—ã–∑–¥—ã “±–º—ã—Ç“õ—ã“£—ã–∑ –∫–µ–ª–µ—Ç—ñ–Ω—ñ–Ω–µ —Å–µ–Ω—ñ–º–¥—ñ—Å—ñ–∑ –±–µ?"""
successReset = """\
–ö—ñ—Ç–∞–ø—Ç—ã –æ“õ—ã“ì–∞–Ω —Å–æ“£ —Å–∞–Ω–∞“£ –±“±–ª—ã“£“ì—ã—Ä–ª–∞–Ω—ã–ø –±–∞—Ä–∞ –∂–∞—Ç—ã—Ä... –ñ–∞—É—ã–Ω–≥–µ—Ä–ª—ñ–∫ –¥–∞“ì–¥—ã–ª–∞—Ä—ã“£–¥—ã “±–º—ã—Ç—ã–ø –±–∞—Ä–∞ –∂–∞—Ç—ã—Ä—Å—ã–Ω. –°—ñ–∑–≥–µ –±–∞—Ä–ª—ã“õ –∂–æ–ª–¥–∞—Ä “õ–∞–π—Ç–∞–¥–∞–Ω –∞—à—ã“õ."""
canceledReset = "–ö—ñ—Ç–∞–ø –æ—Å—ã–Ω–¥–∞ “õ–∞–ª–∞–¥—ã. “ö–∞–ª–∞“ì–∞–Ω —É–∞“õ—ã—Ç—ã“£—ã–∑–¥–∞ –∫–µ–ª–¥—ñ“£—ñ–∑."
increasedCharacteristic = "–°—ñ–∑ –¥–∞“ì–¥—ã“£—ã–∑–¥—ã –∞—Ä—Ç—Ç—ã—Ä–¥—ã“£—ã–∑: ${increased_value}${increased_icon}."
currentCharacteristics = """\
“ö–∞–∑—ñ—Ä–≥—ñ —Å–∏–ø–∞—Ç—Ç–∞–º–∞–ª–∞—Ä—ã“£—ã–∑: ${strength_value}${strength_icon}${agility_value}${agility_icon}${wisdom_value}${wisdom_icon}"""
chooseCharacteristic = """\
–ù–µ–Ω—ñ “Ø–π—Ä–µ“£–≥—ñ“£—ñ–∑ –∫–µ–ª–µ—Ç—ñ–Ω—ñ“£—ñ–∑–¥—ã —Ç–∞“£–¥–∞“£—ã–∑:
(${strength_icon}>${agility_icon}>${wisdom_icon}>${strength_icon})"""
notEnoughCharacteristicPoints = "–°—ñ–∑ ”©–∑ —à–µ–≥—ñ“£—ñ–∑–≥–µ –∂–µ—Ç—Ç—ñ“£—ñ–∑! –ï–≥–µ—Ä —Å—ñ–∑ –∂–µ–∫–ø–µ-–∂–µ–∫ —Å—Ç–∏–ª—ñ“£—ñ–∑–¥—ñ ”©–∑–≥–µ—Ä—Ç–∫—ñ“£—ñ–∑ –∫–µ–ª—Å–µ, ¬´“∞–º—ã—Ç—É –∫—ñ—Ç–∞–±—ã–Ω¬ª –ø–∞–π–¥–∞–ª–∞–Ω—ã“£—ã–∑."
notEnoughMoney = "“∞–º—ã—Ç—É –∫—ñ—Ç–∞–±—ã–Ω –∞–ª—É“ì–∞ –∞“õ—à–∞“£ –∂–µ—Ç–ø–µ–π–¥—ñ! ${money_icon}${money_count} –∫–µ—Ä–µ–∫"
profileLevelUp = "–°—ñ–∑ ”©–∑ –¥–∞“ì–¥—ã–ª–∞—Ä—ã“£—ã–∑–¥—ã –∂–µ—Ç—ñ–ª–¥—ñ—Ä–µ –∞–ª–∞—Å—ã–∑! –ë–∞—Å—ã“£—ã–∑ ${level_up_command}"
confirmButton = "üìñ–û“õ—É"
cancelButton = "‚ùå–ö–µ–ª–µ—Å—ñ –∂–æ–ª—ã"
strengthButton = "+1${strength_icon}"
agilityButton = "+1${agility_icon}"
wisdomButton = "+1${wisdom_icon}"
