joinRaidEvent = "–†–µ–π–¥–∫–µ “õ–æ—Å—ã–ª—Éüó° ${energy_icon}${energy_cost}%"
userAlreadyInOtherEvent = "‚ùå–°—ñ–∑ –±–∞—Å“õ–∞ —à–∞—Ä–∞“ì–∞ “õ–∞—Ç—ã—Å—ã–ø –∂–∞—Ç—ã—Ä—Å—ã–∑!"
expiredRaid = "‚ùå–†–µ–π–¥ –∞—è“õ—Ç–∞–ª–¥—ã!"
raidInProcess = "‚ùå–†–µ–π–¥ –±–∞—Å—Ç–∞–ª—ã–ø –∫–µ—Ç—Ç—ñ"
successRaid = [
    "–®–∞—Ä–∞ –∞—è“õ—Ç–∞–ª–¥—ã! –†–µ–π–¥ —Å”ô—Ç—Ç—ñ ”©—Ç—Ç—ñ.",
    "–ë“±–ª —ç–ø–∏–∫–∞–ª—ã“õ —à–∞–π“õ–∞—Å –±–æ–ª–¥—ã! –°—ñ–∑ –∂–µ—Ç—ñ—Å—Ç—ñ–∫–∫–µ –∂–µ—Ç—Ç—ñ“£—ñ–∑, –º—ñ–Ω–µ, —Å—ñ–∑–¥—ñ“£ —Å—ã–π–ª—ã“ì—ã“£—ã–∑!",
    "“ö–∞—Ä—Å—ã–ª–∞—Å—Ç–∞—Ä –∂–µ“£—ñ–ª–¥—ñ! –ê–ª —Å—ñ–∑ –±–æ“õ –º“±—Ä—ã–Ω –µ–º–µ—Å –µ–∫–µ–Ω—Å—ñ–∑!"
]
failureRaid = [
    "–Ü–∑–¥–µ—É—à—ñ–ª–µ—Ä —Ä–µ–π–¥—Ç–µ —Å”ô—Ç—Å—ñ–∑–¥—ñ–∫–∫–µ “±—à—ã—Ä–∞–¥—ã. –ë—ñ–∑ —Å—ñ–∑–≥–µ –∞“õ—à–∞–Ω—ã –Ω–µ “Ø—à—ñ–Ω —Ç”©–ª–µ–ø –∂–∞—Ç—ã—Ä–º—ã–∑?",
    "–≠—Ö, —Å”ô—Ç—Å—ñ–∑–¥—ñ–∫. –ú“Ø–º–∫—ñ–Ω –∫”©–±—ñ—Ä–µ–∫ —ñ–∑–¥–µ—É—à—ñ–ª–µ—Ä–¥—ñ –∂–∏–Ω–∞—É –∫–µ—Ä–µ–∫ —à—ã“ì–∞—Ä?"
]
zeroParticipants = [
    "–¢–∞–ø—Å—ã—Ä—ã—Å—Ç—ã –µ—à–∫—ñ–º “õ–∞–±—ã–ª–¥–∞–º–∞–¥—ãüò¢–ë“±–ª –∂–æ–ª—ã –∞“õ—à–∞–Ω—ã –µ—à–∫—ñ–º –∞–ª–º–∞–π–¥—ã."
]
successContrabandForPersonage = [
    "${personage_badge_with_name} ”©—Ä—ñ—Å—Ç–µ <b>${contraband_name}</b> —Ç–∞–±–∞–¥—ã! –Ü—à—ñ–Ω–¥–µ –±—ñ—Ä–¥–µ“£–µ —à—ã“£“ì—ã—Ä–∞–π–¥—ã...üì¶"
]
