contrabandFoundPrivateMessage = """\
<b>${contraband_name}</b>

–¢—ã –æ–±–Ω–∞—Ä—É–∂–∏–ª –ø–æ—Ç–µ—Ä—è–Ω–Ω—É—é –∫–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥—É —Å –ß—ë—Ä–Ω–æ–≥–æ –†—ã–Ω–∫–∞. –ö–∞–∂–µ—Ç—Å—è –∫—Ä–æ–º–µ –∑–∞—â–∏—Ç–Ω—ã—Ö –º–µ—Ö–∞–Ω–∏–∑–º–æ–≤ —Ç—É—Ç –µ—â—ë –∏ –∫–∞–∫–∞—è-—Ç–æ –Ω–µ–∏–∑–≤–µ—Å—Ç–Ω–∞—è –º–∞–≥–∏—è... \
–í—Å–∫—Ä—ã–≤–∞—Ç—å —Å–∞–º–æ–º—É –∫—Ä–∞–π–Ω–µ –æ–ø–∞—Å–Ω–æ, –∑–∞—Ç–æ –≤—Å–µ–≥–¥–∞ –º–æ–∂–Ω–æ –æ—Ç–¥–∞—Ç—å –µ–≥–æ –≤–ª–∞–¥–µ–ª—å—Ü–∞–º –∑–∞ –≤–æ–∑–Ω–∞–≥—Ä–∞–∂–¥–µ–Ω–∏–µ

–ö–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥–∞ –æ–∫–æ–Ω—á–∞—Ç–µ–ª—å–Ω–æ —Ä–∞–∑–ª–æ–∂–∏—Ç—Å—è –æ—Ç –≤–æ–∑–¥–µ–π—Å—Ç–≤–∏—è –º–∞–≥–∏–∏ —á–µ—Ä–µ–∑ ${time_left}"""

commonChestName = "üì¶–ü–æ–¥–æ–∑—Ä–∏—Ç–µ–ª—å–Ω—ã–π —Å–≤—ë—Ä—Ç–æ–∫"
rareChestName = "üîí–¢—è–∂—ë–ª—ã–π —Å–µ–π—Ñ"
epicChestName = "üëÅ–®–µ–ø—á—É—â–∏–π —Å—É–Ω–¥—É–∫"

forceOpenButton = "üîì –í—Å–∫—Ä—ã—Ç—å —Å–∞–º–æ–º—É (${chance}%)"
sellToMarketButton = "üí∞ –ü—Ä–æ–¥–∞—Ç—å (${money_icon}${price})"
openAsReceiverButton = "üîß –í—Å–∫—Ä—ã—Ç—å –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç–∞–º–∏ (${chance}%)"

openSuccess = [
    "–õ–æ–≤–∫–æ—Å—Ç—å —Ä—É–∫ –∏ –Ω–∏–∫–∞–∫–æ–≥–æ –º–æ—à–µ–Ω–Ω–∏—á–µ—Å—Ç–≤–∞!\n${rewards}",
    "–î–∞ —Ç—ã —é–≤–µ–ª–∏—Ä!\n${rewards}",
    "–†–∞–∑ —Ä–∞–∑ –∏ –≥–æ—Ç–æ–≤–æ!\n${rewards}",
]

openFailure = [
    "–ö–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥–∞ –≤–∑–æ—Ä–≤–∞–ª–∞—Å—å —É —Ç–µ–±—è –≤ —Ä—É–∫–∞—Ö!\n${penalty}",
    "–ò–∑ –∫–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥—ã –≤—ã—Ä–≤–∞–ª—Å—è –∫–ª—É–± –µ–¥–∫–æ–≥–æ –¥—ã–º–∞.\n${penalty}",
    "–í—Å–ø—ã—à–∫–∞ —Å–≤–µ—Ç–∞ —á—É—Ç—å –Ω–µ –æ—Å—Ç–∞–≤–∏–ª–∞ —Ç–µ–±—è –±–µ–∑ –ø–∞–ª—å—Ü–µ–≤.\n${penalty}",
]

penaltyGoldLoss = "-${money_icon}${amount}"
penaltyNothing = "–ö–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥–∞ —É–Ω–∏—á—Ç–æ–∂–µ–Ω–∞, –Ω–æ —Ç–µ–±–µ –ø–æ–≤–µ–∑–ª–æ –æ—Å—Ç–∞—Ç—å—Å—è –≤ –∂–∏–≤—ã—Ö."

sellSuccess = "–Ø—â–∏–∫ –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω –Ω–∞ —á—ë—Ä–Ω—ã–π —Ä—ã–Ω–æ–∫. +${money_icon}${sell_price}"

receiverNotification = """\
<b>${contraband_name}</b>.

–ö–∞–∂–µ—Ç—Å—è <code>${finder}</code> –Ω–∞—à—ë–ª –∫–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥—É –ß—ë—Ä–Ω–æ–≥–æ –†—ã–Ω–∫–∞ –∏ –ø–µ—Ä–µ–¥–∞–ª –µ—ë –≤–ª–∞–¥–µ–ª—å—Ü–∞–º, –Ω–æ –æ–Ω–∏ –Ω–∏—á–µ–≥–æ –Ω–µ —Å–º–æ–≥–ª–∏ —Å–¥–µ–ª–∞—Ç—å —Å –¥–∏–∫–æ–π –º–∞–≥–∏–µ–π.

–¢–µ–±–µ –ø—Ä–µ–¥–æ—Å—Ç–∞–≤—è—Ç –Ω–∞–±–æ—Ä –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç–æ–≤ –∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –∑–∞–±—Ä–∞—Ç—å —á–∞—Å—Ç—å —Å–æ–¥–µ—Ä–∂–∏–º–æ–≥–æ, –Ω–æ –≤—Å—ë –º–æ–∂–µ—Ç –∑–∞–∫–æ–Ω—á–∏—Ç—Å—è –Ω–µ—É–¥–∞—á–µ–π.

–ö–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥–∞ –æ–∫–æ–Ω—á–∞—Ç–µ–ª—å–Ω–æ —Ä–∞–∑–ª–æ–∂–∏—Ç—Å—è –æ—Ç –≤–æ–∑–¥–µ–π—Å—Ç–≤–∏—è –º–∞–≥–∏–∏ —á–µ—Ä–µ–∑ ${time_left}"""

echoToFinderSuccess = "üì¨ –ù–æ–≤–æ—Å—Ç–∏ —Å —á—ë—Ä–Ω–æ–≥–æ —Ä—ã–Ω–∫–∞: <code>${receiver}</code> —É—Å–ø–µ—à–Ω–æ –≤—Å–∫—Ä—ã–ª —Ç–≤–æ–π <b>${contraband_name}</b>. –ù—É –∏ –ø–æ–∂–∞–ª—É–π—Å—Ç–∞. –ù—É –∏ –Ω–µ –Ω—É–∂–Ω–æ."
echoToFinderFailure = "üì¨ –ù–æ–≤–æ—Å—Ç–∏ —Å —á—ë—Ä–Ω–æ–≥–æ —Ä—ã–Ω–∫–∞: <code>${receiver}</code> –ø–æ–ø—ã—Ç–∞–ª—Å—è –≤—Å–∫—Ä—ã—Ç—å —Ç–≤–æ–π <b>${contraband_name}</b>... –∏ –≤—Å—ë –≤–∑–æ—Ä–≤–∞–ª–æ—Å—å."

contrabandExpired = "‚è∞ –ö–æ–Ω—Ç—Ä–∞–±–∞–Ω–¥–∞ <b>${contraband_name}</b> —Ä–∞–∑–ª–æ–∂–∏–ª–∞—Å—å –ø–æ–¥ –¥–µ–π—Å—Ç–≤–∏–µ–º –º–∞–≥–∏–∏... –≤ —Å–ª–µ–¥—É—é—â–∏–π —Ä–∞–∑ –±—É–¥–µ—à—å –±—ã—Å—Ç—Ä–µ–µ."

rewardGold = "+${money_icon}${amount}"
rewardItem = "<code>${item_name}</code>"
rewardEnergy = "+${amount}${energy_icon}"

contrabandAlreadyProcessed = "–≠—Ç–æ—Ç —è—â–∏–∫ —É–∂–µ –æ–±—Ä–∞–±–æ—Ç–∞–Ω."
contrabandExpiredError = "–Ø—â–∏–∫ –∏—Å—Ç—ë–∫ –∏ —Ä–∞—Å—Å—ã–ø–∞–ª—Å—è –≤ –ø—ã–ª—å."
