registeredGroupInfo = """\
<code>${group_name_with_badge}</code>

–ö–∞–∑–Ω–∞: ${money}${money_icon}
–£—á–∞—Å—Ç–Ω–∏–∫–∏: ${members_count}

üìä–°—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ –≥—Ä—É–ø–ø—ã: ${group_stats_command}
‚öôÔ∏è–ù–∞—Å—Ç—Ä–æ–π–∫–∏: ${group_settings_command}
–ö–æ–º–º–∞–Ω–¥—ã –¥–ª—è –≥—Ä—É–ø–ø—ã: ${group_commands_command}
"""
unregisteredGroupInfo = """\
<code>${group_name_with_badge}</code>

–ö–∞–∑–Ω–∞: ${money}${money_icon}

–ó–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞—Ç—å –≥—Ä—É–ø–ø—É: ${register_group_command}

üìä–°—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ –≥—Ä—É–ø–ø—ã: ${group_stats_command}
‚öôÔ∏è–ù–∞—Å—Ç—Ä–æ–π–∫–∏: ${group_settings_command}
–í–ª–æ–∂–∏—Ç—å –¥–µ–Ω—å–≥–∏: <code>${donate_money_command} [—Å—É–º–º–∞]</code>
"""

groupRegistration = """\
–î–ª—è —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏ –≥—Ä—É–ø–ø—ã –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ —É—Å—Ç–∞–Ω–æ–≤–∏—Ç—å —Ç—ç–≥ –≥—Ä—É–ø–ø—ã <code>${register_group_command} —Ç—ç–≥</code>. \
–¢—ç–≥ –¥–æ–ª–∂–µ–Ω —Å—Ç–æ—Å—Ç–æ—è—Ç—å –∏–∑ 3-4 –∑–∞–≥–ª–∞–≤–Ω—ã—Ö –±—É–∫–≤ –ª–∞—Ç–∏–Ω—Å–∫–æ–≥–æ –∞–ª—Ñ–∞–≤–∏—Ç–∞.
–°—Ç–æ–∏–º–æ—Å—Ç—å: ${money}${money_icon}"""
alreadyRegisteredGroup = "–ì—Ä—É–ø–ø–∞ —É–∂–µ –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–Ω–∞"
registrationPersonageInAnotherGroup = "–†–µ–≥–∏—Å—Ç—Ä–∏—Ä—É—é—â–∏–π –ø–µ—Ä—Å–æ–Ω–∞–∂ –Ω–µ –¥–æ–ª–∂–µ–Ω –±—ã—Ç—å —É—á–∞—Å—Ç–Ω–∏–∫–æ–º –¥—Ä—É–≥–æ–π –≥—Ä—É–ø–ø—ã!"
notEnoughMoneyForGroupRegistration = "–î–ª—è —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏ –≥—Ä—É–ø–ø—ã –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ ${money}${money_icon} –≤ –∫–∞–∑–Ω–µ –≥—Ä—É–ø–ø—ã!"
incorrectTag = "–ù–µ–ø—Ä–∞–≤–∏–ª—å–Ω–æ —É–∫–∞–∑–∞–Ω —Ç—ç–≥, –æ–Ω –¥–æ–ª–∂–µ–Ω —Å–æ—Å—Ç–æ—è—Ç—å –∏–∑ 3-4 –∑–∞–≥–ª–∞–≤–Ω—ã—Ö –±—É–∫–≤ –ª–∞—Ç–∏–Ω—Å–∫–æ–≥–æ –∞–ª—Ñ–∞–≤–∏—Ç–∞"
tagAlreadyTaken = "–¢–∞–∫–æ–π —Ç—ç–≥ —É–∂–µ –∑–∞–Ω—è—Ç"
successGroupRegistration = "–ì—Ä—É–ø–ø–∞ —É—Å–ø–µ—à–Ω–æ –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–Ω–∞! –í—Å—Ç—É–ø–∏—Ç—å –≤ –≥—Ä—É–ø–ø—É –º–æ–∂–Ω–æ —Å –ø–æ–º–æ—â—å—é ${group_join_command}"

joinPersonageAlreadyInGroup = "–¢—ã —É–∂–µ —Å–æ—Å—Ç–æ–∏—à—å –≤ —ç—Ç–æ–π –≥—Ä—É–ø–ø–µ!"
joinPersonageInAnotherGroup = "–¢—ã —É–∂–µ —Å–æ—Å—Ç–æ–∏—à—å –≤ –¥—Ä—É–≥–æ–π –≥—Ä—É–ø–ø–µ!"
joinPersonageTimeout = "–¢—ã –Ω–µ –º–æ–∂–µ—à—å –≤—Å—Ç—É–ø–∏—Ç—å –≤ –≥—Ä—É–ø–ø—É –≤ —Ç–µ—á–µ–Ω–∏e ${duration}"
groupNotRegisteredAtJoin = "–ì—Ä—É–ø–ø–∞ –¥–æ–ª–∂–Ω–∞ –±—ã—Ç—å –∑–∞—Ä–µ–≥–∏—Å—Ç—Ä–∏—Ä–æ–≤–∞–Ω–∞ –¥–ª—è –≤—Å—Ç—É–ø–ª–µ–Ω–∏—è: ${register_group_command}"
successJoinGroup = "<code>${personage_badge_with_name}</code> —Ç–µ–ø–µ—Ä—å —Å–æ—Å—Ç–æ–∏—Ç –≤ –≥—Ä—É–ø–ø–µ <code>${group_name_with_badge}</code>!"
joinPersonageConfirmationRequired = """\
–î–ª—è –≤—Å—Ç—É–ø–ª–µ–Ω–∏—è <code>${personage_badge_with_name}</code> –≤ –≥—Ä—É–ø–ø—É –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä–∞"""
joinGroupConfirmButton = "‚úÖ–ü–æ–¥—Ç–≤–µ—Ä–¥–∏—Ç—å"
joinGroupCancelButton = "‚ùå–û—Ç–∫–∞–∑–∞—Ç—å"
joinPersonageConfirmed = """\
–†–∞–∑—Ä–µ—à–µ–Ω–∏–µ –Ω–∞ –≤—Å—Ç—É–ø–ª–µ–Ω–∏–µ –¥–ª—è <code>${personage_badge_with_name}</code> –≤ –≥—Ä—É–ø–ø—É –ø–æ–ª—É—á–µ–Ω–æ \
–æ—Ç <code>${admin_badge_with_name}</code>"""
joinPersonageCanceled = "–í—Å—Ç—É–ø–ª–µ–Ω–∏–µ –≤ –≥—Ä—É–ø–ø—É <code>${personage_badge_with_name}</code> –æ—Ç–º–µ–Ω–µ–Ω–æ"
joinConfirmNotMember = "–î–ª—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è –Ω–∞–¥–æ —Å–æ—Å—Ç–æ—è—Ç—å –≤ –≥—Ä—É–ø–ø–µ"

leaveGroupSuccess = "<code>${personage_badge_with_name}</code> –±–æ–ª—å—à–µ –Ω–µ —Å–æ—Å—Ç–æ–∏—Ç –≤ –≥—Ä—É–ø–ø–µ. –í—Å—Ç—É–ø–ª–µ–Ω–∏–µ –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω–æ –Ω–∞ ${duration}"
leaveGroupNotMember = "–¢—ã –Ω–µ —Å–æ—Å—Ç–æ–∏—à—å –≤ —ç—Ç–æ–π –≥—Ä—É–ø–ø–µ"
leaveGroupLastMemberConfirmation = "–ü–æ—Å–ª–µ —Ç–µ–±—è –≤ –≥—Ä—É–ø–ø–µ –Ω–µ –±—É–¥–µ—Ç —É—á–∞—Å—Ç–Ω–∏–∫–æ–≤, –∏ –æ–Ω–∞ –±—É–¥–µ—Ç —Å–Ω—è—Ç–∞ —Å —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏"
leaveGroupConfirmButton = "‚úÖ–ü–æ–∫–∏–Ω—É—Ç—å"
leaveGroupCancelButton = "‚ùå–û—Ç–º–µ–Ω–∏—Ç—å"
leaveGroupLastMemberSuccess = """
<code>${personage_badge_with_name}</code> –±–æ–ª—å—à–µ –Ω–µ —Å–æ—Å—Ç–æ–∏—Ç –≤ –≥—Ä—É–ø–ø–µ. \
<code>${group_name_with_badge}</code> —Å–Ω—è—Ç–∞ —Å —Ä–µ–≥–∏—Å—Ç—Ä–∞—Ü–∏–∏.
–í—Å—Ç—É–ø–ª–µ–Ω–∏–µ –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω–æ –Ω–∞ ${duration}"""
leaveGroupCancel = "–¢—ã –æ—Å—Ç–∞—ë—à—å—Å—è –≤ –≥—Ä—É–ø–ø–µ"

successDonate = "–í –≥—Ä—É–ø–ø—É –≤–ª–æ–∂–µ–Ω–æ ${money}${money_icon} –æ—Ç ${personage_badge_with_name}!"
notEnoughMoneyForDonate = "–ù–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –¥–µ–Ω–µ–≥"
successGiveMoney = "${giver_badge_with_name} –≤—ã–¥–∞—ë—Ç –∏–∑ –≥—Ä—É–ø–ø—ã ${money}${money_icon} –¥–ª—è ${acceptor_badge_with_name}!"
notEnoughMoneyForGive = "–ù–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –¥–µ–Ω–µ–≥ –≤ –∫–∞–∑–Ω–µ –≥—Ä—É–ø–ø—ã"
giveMoneyPersonageNotMember = "–ü–æ–ª—É—á–∞—Ç–µ–ª—å –¥–æ–ª–∂–µ–Ω —Å–æ—Å—Ç–æ—è—Ç—å –≤ –≥—Ä—É–ø–ø–µ"
giverNotMember = "–î–ª—è –≤—ã–¥–∞—á–∏ –¥–µ–Ω–µ–≥ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ —Å–æ—Å—Ç–æ—è—Ç—å –≤ –≥—Ä—É–ø–ø–µ"
incorrectAcceptor = """\
–ù–µ–æ–±—Ö–æ–¥–∏–º–æ —É–∫–∞–∑–∞—Ç—å –∫–æ–º—É –≤—ã–¥–∞—é—Ç—Å—è –¥–µ–Ω—å–≥–∏, –ª–∏–±–æ –æ—Ç–≤–µ—Ç–æ–º –Ω–∞ —Å–æ–æ–±—â–µ–Ω–∏–µ –ª–∏–±–æ —á–µ—Ä–µ–∑ —É–ø–æ–º–∏–Ω–∞–Ω–∏–µ. –ù–∞–ø—Ä–∏–º–µ—Ä:
<code>${give_money_command} 100 @user</code>"""
acceptorNotFound = """\
–ö —Å–æ–∂–∞–ª–µ–Ω–∏—é, –º—ã –Ω–µ —Å–º–æ–≥–ª–∏ –Ω–∞–π—Ç–∏ –∫–æ–º—É –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –¥–µ–Ω—å–≥–∏. \
–í–æ–∑–º–æ–∂–Ω–æ —Ç–≤–æ–π —Ç–æ–≤–∞—Ä–∏—â –µ—â—ë –Ω–µ –ø–æ—Å–µ—â–∞–ª –¥–∞–Ω–Ω—É—é —Ç–∞–≤–µ—Ä–Ω—É –∏–ª–∏ —Å–º–µ–Ω–∏–ª –∏–º—è."""
incorrectAmount = "–ù–µ–ø—Ä–∞–≤–∏–ª—å–Ω–æ —É–∫–∞–∑–∞–Ω–∞ —Å—É–º–º–∞"

groupCommands = """\
–ö–æ–º–º–∞–Ω–¥—ã –¥–ª—è –≥—Ä—É–ø–ø—ã:

<code>${group_join_command}</code> - –≤—Å—Ç—É–ø–∏—Ç—å –≤ –≥—Ä—É–ø–ø—É
<code>${group_leave_command}</code> - –ø–æ–∫–∏–Ω—É—Ç—å –≥—Ä—É–ø–ø—É
<code>${donate_money_command} [—Å—É–º–º–∞]</code> - –≤–ª–æ–∂–∏—Ç—å –¥–µ–Ω—å–≥–∏ –≤ –≥—Ä—É–ø–ø—É
<code>${give_money_command} [—Å—É–º–º–∞] @user</code> - –≤—ã–¥–∞—Ç—å –¥–µ–Ω—å–≥–∏ –∏–∑ –≥—Ä—É–ø–ø—ã"""
