groupInfo = """\
<code>${group_name_with_badge}</code>

üìä–°—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ –≥—Ä—É–ø–ø—ã: ${group_stats_command}
‚öôÔ∏è–ù–∞—Å—Ç—Ä–æ–π–∫–∏: ${group_settings_command}
"""

groupSettings = """\
‚öôÔ∏è–ù–∞—Å—Ç—Ä–æ–π–∫–∏ –≥—Ä—É–ø–ø—ã ${group_name_with_badge}:
${optional_group_is_hidden_description}
–ò–∑–º–µ–Ω–∏—Ç—å –∏–º—è –≥—Ä—É–ø–ø—ã: <code>${change_group_name_command} [–∏–º—è_–≥—Ä—É–ø–ø—ã]</code>
–ß–∞—Å–æ–≤–æ–π –ø–æ—è—Å: ${time_zone}
–ò–∑–º–µ–Ω–µ–Ω–∏–µ —á–∞—Å–æ–≤–æ–≥–æ –ø–æ—è—Å–∞: <code>${set_time_zone_command} [—á–∞—Å–æ–≤–æ–π_–ø–æ—è—Å]</code>

–ò–Ω—Ç–µ—Ä–≤–∞–ª—ã –¥–ª—è —Ä–µ–π–¥–æ–≤:"""
groupIsHiddenDescription = "\n–ì—Ä—É–ø–ø–∞ —Å–∫—Ä—ã—Ç–∞ –∏–∑ —Ä–µ–π—Ç–∏–Ω–≥–æ–≤ –∏ –∞–∫—Ç–∏–≤–Ω–æ—Å—Ç–µ–π. –ê–∫—Ç–∏–≤–Ω–æ—Å—Ç–∏ –Ω–µ —É—á–∏—Ç—ã–≤–∞—é—Ç—Å—è –≤ –≥–ª–æ–±–∞–ª—å–Ω–æ–π —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–µ.\n"
eventIntervalButton = "${start_hour} ‚Äî ${end_hour} ${enabled_icon}"
incorrectTimeZone = "–ù–µ–ø—Ä–∞–≤–∏–ª—å–Ω–æ —É–∫–∞–∑–∞–Ω —á–∞—Å–æ–≤–æ–π –ø–æ—è—Å, —ç—Ç–æ –¥–æ–ª–∂–Ω–æ –±—ã—Ç—å —Ü–µ–ª–æ–µ —á–∏—Å–ª–æ –æ—Ç ${min_time_zone} –¥–æ ${max_time_zone}"
zeroEnabledEventIntervals = "–•–æ—Ç—è –±—ã –æ–¥–∏–Ω –∏–Ω—Ç–µ—Ä–≤–∞–ª –¥–æ–ª–∂–µ–Ω –±—ã—Ç—å –≤–∫–ª—é—á—ë–Ω"
incorrectSetTimeZoneCommand = """\
–ö–æ–º–∞–Ω–¥–∞ –≤–≤–æ–¥–∏—Ç—Å—è –≤ —Ñ–æ—Ä–º–∞—Ç–µ: <code>${set_time_zone_command} [—á–∞—Å–æ–≤–æ–π_–ø–æ—è—Å]</code>. –ß–∞—Å–æ–≤–æ–π –ø–æ—è—Å —è–≤–ª—è–µ—Ç—Å—è —Ü–µ–ª—ã–º —á–∏—Å–ª–æ–º."""
successChangeTimeZone = "–ß–∞—Å–æ–≤–æ–π –ø–æ—è—Å –∏–∑–º–µ–Ω—ë–Ω."

changeNameInvalidFormat = """
–ß—Ç–æ–±—ã –∏–∑–º–µ–Ω–∏—Ç—å –∏–º—è –≥—Ä—É–ø–ø—ã –≤–≤–µ–¥–∏—Ç–µ –∫–æ–º–∞–Ω–¥—É –≤ —Å–ª–µ–¥—É—é—â–µ–º —Ñ–æ—Ä–º–∞—Ç–µ: <code>${change_group_name_command} [–∏–º—è_–≥—Ä—É–ø–ø—ã]</code>"""
changeNameInvalidSymbols = """
–í –∏–º–µ–Ω–∏ –≥—Ä—É–ø–ø—ã –º–æ–∂–Ω–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å —Ç–æ–ª—å–∫–æ: <code>–∫–∏—Ä–∏–ª–ª–∏—Ü—É, –ª–∞—Ç–∏–Ω–∏—Ü—É, —Ü–∏—Ñ—Ä—ã, —Å–∏–º–≤–æ–ª—ã _-.#‚Ññ –∏ –ø—Ä–æ–±–µ–ª</code>"""
changeNameInvalidLength = """
–î–ª–∏–Ω–∞ –∏–º–µ–Ω–∏ –≥—Ä—É–ø–ø—ã –¥–æ–ª–∂–Ω–∞ –±—ã—Ç—å –æ—Ç ${min_name_length} –¥–æ ${max_name_length} —Å–∏–º–≤–æ–ª–æ–≤"""
successChangeName = "–ò–º—è –≥—Ä—É–ø–ø—ã –∏–∑–º–µ–Ω–µ–Ω–æ –Ω–∞ <b>${name}</b>"

groupIsHidden = "–¢–µ–ø–µ—Ä—å –≥—Ä—É–ø–ø–∞ —Å–∫—Ä—ã—Ç–∞ –∏–∑ –æ–±—â–∏—Ö —Ä–µ–π—Ç–∏–Ω–≥–æ–≤ –∏ –∞–∫—Ç–∏–≤–Ω–æ—Å—Ç–µ–π"
groupIsNotHidden = "–¢–µ–ø–µ—Ä—å –≥—Ä—É–ø–ø–∞ –≤–∏–¥–Ω–∞ –≤ –æ–±—â–∏—Ö —Ä–µ–π—Ç–∏–Ω–≥–∞—Ö –∏ –∞–∫—Ç–∏–≤–Ω–æ—Å—Ç—è—Ö"
forbiddenHidden = "–î–∞–Ω–Ω–æ–π –≥—Ä—É–ø–ø–µ –∑–∞–ø—Ä–µ—â–µ–Ω–æ –º–µ–Ω—è—Ç—å –Ω–∞—Å—Ç—Ä–æ–π–∫–∏ –≤–∏–¥–∏–º–æ—Å—Ç–∏"

