# TODO —Ö–∞—Ä–∞–∫—Ç–µ—Ä–∏—Å—Ç–∏–∫–∏
itemWithoutModifiers = "${slots} ${item} ${characteristics}"
itemWithPrefixModifier = "${slots} ${prefix_modifier} ${item} ${characteristics}"
itemWithSuffixModifier = "${slots} ${item} ${suffix_modifier} ${characteristics}"
itemWithPrefixAndSuffixModifier = "${slots} ${prefix_modifier} ${item} ${suffix_modifier} ${characteristics}"
itemWithTwoPrefixModifiers = "${slots} ${prefix_modifier_one} ${prefix_modifier_two} ${item} ${characteristics}"
characteristics = "${not_zero_attack}"
attack = "${attack_icon}${attack_value}"
itemInBag = "${item} ${put_on_command}"
personageFreeSlot = "${slot} <i>–ü—É—Å—Ç–æ</i>"

inventory = """\
<b>üë§–°–Ω–∞—Ä—è–∂–µ–Ω–∏–µ:</b>
${equipped_items}
${personage_free_slots}

<b>üéí–†—é–∫–∑–∞–∫ (${items_in_bag_count}/${max_items_in_bag}):</b>
${items_in_bag}"""

personageMissingItem = "–£ –≤–∞—Å –Ω–µ—Ç —Ç–∞–∫–æ–≥–æ –ø—Ä–µ–¥–º–µ—Ç–∞"
alreadyEquipped = "–í—ã —É–∂–µ —ç–∫–∏–ø–∏—Ä–æ–≤–∞–ª–∏ –¥–∞–Ω–Ω—ã–π –ø—Ä–µ–¥–º–µ—Ç"
requiredFreeSlots = "–ó–∞–Ω—è—Ç—ã –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã–µ —Å–ª–æ—Ç—ã: ${busy_slots}"
successPutOn = "–£—Å–ø–µ—à–Ω–æ —ç–∫–∏–ø–∏—Ä–æ–≤–∞–Ω–æ: ${item}"