# TODO —Ö–∞—Ä–∞–∫—Ç–µ—Ä–∏—Å—Ç–∏–∫–∏
itemWithoutModifiers = "${object}"
itemWithPrefixModifier = "${prefix_modifier} ${object}"
itemWithSuffixModifier = "${object} ${suffix_modifier}"
itemWithPrefixAndSuffixModifier = "${prefix_modifier} ${object} ${suffix_modifier}"
itemWithTwoPrefixModifiers = "${prefix_modifier_one} ${prefix_modifier_two} ${object}"
fullItem = "${slots} ${item} ${characteristics}"
shortItem = "${item} ${characteristics}"
characteristics = "${not_zero_attack}"
attack = "${attack_icon}${attack_value}"
itemInBag = "${full_item} ${put_on_command} ${drop_command}"
equippedItem = "${full_item} ${take_off_command}"
personageFreeSlot = "${slot} <i>–ü—É—Å—Ç–æ</i>"

inventory = """\
<b>üë§–°–Ω–∞—Ä—è–∂–µ–Ω–∏–µ:</b>
${equipped_items_and_free_slots}

<b>üéí–†—é–∫–∑–∞–∫ (${items_in_bag_count}/${max_items_in_bag}):</b>
${items_in_bag}"""

personageMissingItem = "–£ –≤–∞—Å –Ω–µ—Ç —Ç–∞–∫–æ–≥–æ –ø—Ä–µ–¥–º–µ—Ç–∞"
alreadyEquipped = "–í—ã —É–∂–µ —ç–∫–∏–ø–∏—Ä–æ–≤–∞–ª–∏ –¥–∞–Ω–Ω—ã–π –ø—Ä–µ–¥–º–µ—Ç"
alreadyTakenOff = "–î–∞–Ω–Ω—ã–π –ø—Ä–µ–¥–º–µ—Ç –Ω–µ —ç–∫–∏–ø–µ—Ä–æ–≤–∞–Ω"
notEnoughSpaceInBag = "–í —Ä—é–∑–∫–∞–∫–µ –Ω–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –º–µ—Å—Ç–∞, —á—Ç–æ–±—ã —Å–Ω—è—Ç—å –ø—Ä–µ–¥–º–µ—Ç"
requiredFreeSlots = "–ó–∞–Ω—è—Ç—ã –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã–µ —Å–ª–æ—Ç—ã: ${busy_slots}"
successPutOn = "–£—Å–ø–µ—à–Ω–æ —ç–∫–∏–ø–∏—Ä–æ–≤–∞–Ω–æ: ${item}"
successTakeOff = "–£—Å–ø–µ—à–Ω–æ —Å–Ω—è—Ç–æ: ${item}"


confirmDrop = "–í—ã —Ç–æ—á–Ω–æ —Ö–æ—Ç–∏—Ç–µ –≤—ã–∫–∏–Ω—É—Ç—å ${item}"
confirmDropButton = "‚úÖ–î–∞"
rejectDropButton = "‚ùå–ù–µ—Ç"
successDrop = "–í—ã –≤—ã–∫–∏–Ω—É–ª–∏ ${item}"
rejectedDrop = "–ù–µ –≤ —ç—Ç–æ—Ç —Ä–∞–∑"
