joinRaidEvent = "–ü—Ä–∏—Å–æ–µ–¥–∏–Ω–∏—Ç—å—Å—è –∫ —Ä–µ–π–¥—Éüó°"
raidStartsPrefix = "–ë–∏—Ç–≤–∞ –Ω–∞—á–Ω—ë—Ç—Å—è —á–µ—Ä–µ–∑"
userAlreadyInThisRaid = "–í—ã —É–∂–µ —É—á–∞—Å—Ç–≤—É–µ—Ç–µ –≤ —ç—Ç–æ–º —Ä–µ–π–¥–µ!"
userAlreadyInOtherEvent = "–í—ã —É–∂–µ —É—á–∞—Å—Ç–≤—É–µ—Ç–µ –≤ –¥—Ä—É–≥–æ–º —Å–æ–±—ã—Ç–∏–∏!"
expiredRaid = "–†–µ–π–¥ –∑–∞–≤–µ—Ä—à—ë–Ω!"
raidInProcess = "–†–µ–π–¥ —É–∂–µ –Ω–∞—á–∞–ª—Å—è"
successRaid = [
    "–°–æ–±—ã—Ç–∏–µ –∑–∞–≤–µ—Ä—à–∏–ª–æ—Å—å! –†–µ–π–¥ –±—ã–ª —É—Å–ø–µ—à–µ–Ω.",
    "–≠–ø–∏—á–Ω—ã–π –±—ã–ª –±–æ–π! –í—ã –ø—Ä–µ—É—Å–ø–µ–ª–∏, –≤–æ—Ç –≤–∞—à–∞ –Ω–∞–≥—Ä–∞–¥–∞!",
    "–ü—Ä–æ—Ç–∏–≤–Ω–∏–∫–∏ –ø–æ–≤–µ—Ä–∂–µ–Ω—ã! –ê –≤—ã, –æ–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è, –Ω–µ —Å–æ–ø–ª—è–∫–∏!"
]
failureRaid = [
    "–ò—Å–∫–∞—Ç–µ–ª–∏ –ø—Ä–æ–≤–∞–ª–∏–ª–∏ —Ä–µ–π–¥. –ó–∞ —á—Ç–æ –º—ã –≤–∞–º –¥–µ–Ω—å–≥–∏ –ø–ª–∞—Ç–∏–º?",
    "–≠—Ö, –ø—Ä–æ–≤–∞–ª. –ú–æ–∂–µ—Ç, —Å—Ç–æ–∏—Ç —Å–æ–±—Ä–∞—Ç—å –±–æ–ª—å—à–µ –∏—Å–∫–∞—Ç–µ–ª–µ–π?",
    "–ë–æ–π –±—ã–ª –Ω–µ —Å–∞–º—ã–º —É—Å–ø–µ—à–Ω—ã–º. –¢–µ–ø–µ—Ä—å –≤—ã –ø–æ —É—à–∏ –≤ –¥–µ—Ä—å–º–µ."
]
zeroParticipants = [
    "–ù–∏–∫—Ç–æ –Ω–µ –ø—Ä–∏–Ω—è–ª –∑–∞–∫–∞–∑üò¢–í —ç—Ç–æ—Ç —Ä–∞–∑ –¥–µ–Ω–µ–≥ –Ω–∏–∫—Ç–æ –Ω–µ –ø–æ–ª—É—á–∏—Ç."
]
personageRaidResult = "${dead_icon_or_empty}${personage_badge_with_name}: ${damage_dealt}‚öîÔ∏è ${damage_taken}üõ° +${money}${money_icon}"
raidResult = """\
–ü—Ä–æ—Ç–∏–≤–Ω–∏–∫–∏: ${remain_enemies_health}/${total_enemies_health}‚ù§Ô∏è ${remain_enemies_count}/${total_enemies_count}üëπ

–õ—É—á—à–∏–µ –∏—Å–∫–∞—Ç–µ–ª–∏:
${top_personages_list}${from_new_line_items_for_personages}

–û—Ç—á—ë—Ç –æ —Ä–µ–π–¥–µ: ${raid_report_command}"""
successItemForPersonage = [
    "${personage_badge_with_name} –æ–±–Ω–∞—Ä—É–∂–∏–≤–∞–µ—Ç –Ω–∞ –ø–æ–ª–µ <code>${short_item}</code>! –ù–µ–æ–±—Ö–æ–¥–∏–º–æ –æ–±–º—ã—Ç—å –Ω–∞—Ö–æ–¥–∫—É –≤ —Ç–∞–≤–µ—Ä–Ω–µüçª"
]
notEnoughSpaceInBagForItem = [
    "${personage_badge_with_name} –æ–±–Ω–∞—Ä—É–∂–∏–≤–∞–µ—Ç –Ω–∞ –ø–æ–ª–µ <code>${short_item}</code>, –Ω–æ –Ω–µ –º–æ–∂–µ—Ç —É–Ω–µ—Å—Ç–∏ –∏–∑-–∑–∞ –ø–æ–ª–Ω–æ–≥–æ —Ä—é–∫–∑–∞–∫–∞...üò¢"
]
raidParticipants = "–£—á–∞—Å—Ç–Ω–∏–∫–∏: ${personage_badge_name_list}"
notEnoughEnergy = "–í—ã–≥–ª—è–¥–∏—à—å —É—Å—Ç–∞–≤—à–∏–º! –û—Ç–¥–æ—Ö–Ω–∏ —Ö–æ—Ç—è –±—ã –¥–æ ${energy_icon}${required_energy}%"
report = """\
üìú–í–∞—à –æ—Ç—á—ë—Ç –∑–∞ –ø–æ—Å–ª–µ–¥–Ω–∏–π —Ä–µ–π–¥:
<code>${raid_date_time}</code>

–•–∞—Ä–∞–∫—Ç–µ—Ä–∏—Å—Ç–∏–∫–∏ –≤ —Ä–µ–π–¥–µ:
${attack_icon}${attack_value}${defense_icon}${defense_value}
${strength_icon}${strength_value}${agility_icon}${agility_value}${wisdom_icon}${wisdom_value}

üìä–°—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞:
${normal_attack_icon}–û–±—ã—á–Ω—ã–µ –∞—Ç–∞–∫–∏: ${normal_damage_value} (${normal_damage_count})
${crit_attack_icon}–ö—Ä–∏—Ç–∏—á–µ—Å–∫–∏–µ –∞—Ç–∞–∫–∏: ${crit_damage_value} (${crit_damage_count})
${miss_icon}–ü—Ä–æ–º–∞—Ö–∏: ${misses_count}

${damage_blocked_icon}–£—Ä–æ–Ω–∞ –ø–æ–ª—É—á–µ–Ω–æ: ${damage_blocked_value} (${damage_blocked_count})
${dodge_icon}–£–∫–ª–æ–Ω–µ–Ω–∏—è: ${dodged_damage_value} (${dodged_damage_count})

${health_icon}Ô∏è–ó–¥–æ—Ä–æ–≤—å–µ: ${remain_health}/${max_health}

${money_icon}–ù–∞–≥—Ä–∞–¥–∞: ${reward_value}"""
reportNotPresentForPersonage = "–ù–µ —Å–º–æ–≥–ª–∏ –Ω–∞–π—Ç–∏ —Ç–≤–æ–π –æ—Ç—á—ë—Ç –æ —Ä–µ–π–¥–µ –≤ –∞—Ä—Ö–∏–≤–∞—Ö"
shortPersonageReport = """\
üìú${personage_badge_with_name} ${health_icon}${remain_health}
${normal_attack_icon}${normal_damage_value} (${normal_damage_count}) ${crit_attack_icon}${crit_damage_value} (${crit_damage_count})
${damage_blocked_icon}${damage_blocked_value} (${damage_blocked_count}) ${dodge_icon}${dodged_damage_value} (${dodged_damage_count})
+${reward_value}${money_icon}"""
lastGroupRaidReportNotFound = "–¢—ã –Ω–µ —É—á–∞—Å—Ç–≤–æ–≤–∞–ª –≤ –ø–æ—Å–ª–µ–¥–Ω–µ–º —Ä–µ–π–¥–µ"
