menuHeader = "–°–µ–≥–æ–¥–Ω—è –≤ –º–µ–Ω—é:"
drinks = "–ù–∞–ø–∏—Ç–∫–∏"
mainDishes = "–û—Å–Ω–æ–≤–Ω—ã–µ –±–ª—é–¥–∞"
itemNotInMenu = "–¢–∞–∫–æ–π –ø–æ–∑–∏—Ü–∏–∏ –Ω–µ—Ç –≤ –º–µ–Ω—é!"
notEnoughMoneyDrink = [
    "–¢–µ–±–µ –Ω–µ —Ö–≤–∞—Ç–∞–µ—Ç ${money_icon}${not_enough_money_value}, –∏–¥–∏ –ø–æ—Ä–∞–±–æ—Ç–∞–π, –ø–æ—Ç–æ–º –ø—Ä–∏—Ö–æ–¥–∏ –ø–∏—Ç—å!",
    "–î–∞–Ω–Ω—ã–π –Ω–∞–ø–∏—Ç–æ–∫ —Ç–µ–±–µ —è–≤–Ω–æ –Ω–µ –ø–æ –∫–∞—Ä–º–∞–Ω—É! –û–Ω —Å—Ç–æ–∏—Ç ${money_icon}${item_cost}"
]
notEnoughMoneyMainDish = [
    "–ö—Ç–æ –Ω–µ —Ä–∞–±–æ—Ç–∞–µ—Ç, —Ç–æ—Ç –Ω–µ –µ—Å—Ç! –ó–∞—Ä–∞–±–æ—Ç–∞–π –µ—â—ë ${money_icon}${not_enough_money_value}"
]
orderGiftToDifferentBot = [
    "–ó–∞–∫–∞–∑ –¥–ª—è –¥—Ä—É–≥–æ–≥–æ –±–æ—Ç–∞ –ü–ï–†–ï–î–ï–õ–ê–¢–¨"
]
orderGiftToThisBot = [
    "–ó–∞–∫–∞–∑ –¥–ª—è —ç—Ç–æ–≥–æ –±–æ—Ç–∞ –ü–ï–†–ï–î–ï–õ–ê–¢–¨"
]
order = [
    "${item_name} –¥–ª—è ${mention_acceptor_icon_with_name}!"
]
orderGift = [
    "–ó–∞–∫–∞–∑! ${item_name} –æ—Ç ${mention_giver_icon_with_name} –¥–ª—è ${mention_acceptor_icon_with_name}"
]
expiredOrder = [
    "–ó–∞–∫–∞–∑ —Ç–∞–∫ –¥–æ–ª–≥–æ —Å—Ç–æ—è–ª –±–µ–∑ –¥–µ–ª–∞, —á—Ç–æ –µ–≥–æ —Å—ä–µ–ª –≥–æ–ª–æ–¥–Ω—ã–π –æ—Ñ–∏—Ü–∏–∞–Ω—Ç. –î–µ–Ω–µ–≥ –æ–Ω, –∫ —Å–æ–∂–∞–ª–µ–Ω–∏—é, –Ω–µ –æ—Å—Ç–∞–≤–∏–ª."
]
consumeDrinkButton = "üç∫–í—ã–ø–∏—Ç—å"
consumeMainDishButton = "üçΩ–°—ä–µ—Å—Ç—å"
consumeAlreadyInFinalStatus = "–ó–∞–∫–∞–∑ –∫—É–¥–∞-—Ç–æ –∏—Å–ø–∞—Ä–∏–ª—Å—è... –í–æ–∑–º–æ–∂–Ω–æ –µ–≥–æ —É—Ç–∞—â–∏–ª –±–∞–±–∞–π–∫–∞"
wrongConsumer = "–≠—Ç–æ –Ω–µ —Ç–≤–æ–π –∑–∞–∫–∞–∑!"
orderToUnknownUser = [
    """\
–û—Ñ–∏—Ü–∏–∞–Ω—Ç—ã –Ω–µ –Ω–∞—à–ª–∏ —ç—Ç–æ–≥–æ –ò—Å–∫–∞—Ç–µ–ª—è —Å—Ä–µ–¥–∏ –ø–æ—Å–µ—Ç–∏—Ç–µ–ª–µ–π. \
–í–æ–∑–º–æ–∂–Ω–æ —Ç–≤–æ–π —Ç–æ–≤–∞—Ä–∏—â –µ—â—ë –Ω–µ –ø–æ—Å–µ—â–∞–ª –¥–∞–Ω–Ω—É—é —Ç–∞–≤–µ—Ä–Ω—É –∏–ª–∏ —Å–º–µ–Ω–∏–ª –∏–º—è."""
]
orderIsLocked = "–ó–∞–∫–∞–∑ –≤ –æ–±—Ä–∞–±–æ—Ç–∫–µ, –ø–æ–ø—Ä–æ–±—É–π—Ç–µ –ø–æ–∑–∂–µ."
