initFeedback = """\
Bienvenido al sistema de retroalimentaci칩n de la Taberna de Krezar.
Aqu칤 puedes dejar cualquier sugerencia, reporte de errores u otra cosa relacionada con el juego.

Si tu mensaje es 칰til, podr칤as recibir monedas del juego o insignias como recompensa. Por favor, evita el spam.

Elige un tema para tu mensaje:"""

errorButton = "仇勇Reportar un error"
improvementButton = "游눠Sugerir una idea"
textButton = "游닇Proponer un texto"
otherButton = "游눫Otro"
backButton = "拘勇뀨tr치s"

inputTextSuggestion = """\
Aqu칤 puedes proponer cualquier texto para el juego. Algunos ejemplos:
Incursiones, misiones, frases de la taberna, finales de asalto, comienzos de duelos, finales de duelos, pedidos expirados, \
trabajador del d칤a, pedidos en la taberna, regalos... todo lo que veas en forma de texto."""
inputFeedback = "Escribe tu mensaje:"
feedbackSent = """\
Tu mensaje fue enviado al desarrollador. Si es algo que merece atenci칩n, \
recibir치s respuesta por el canal ${feedback_channel}."""
feedback = """\
<code>${personage_id} ${personage_badge_with_name}</code>

${feedback_theme}

${feedback_text}"""
cancelFeedback = "Ser치 para otra vez."
invalidTheme = "Selecciona un tema de la lista:"
feedbackErrorSent = "No se pudo enviar el mensaje. Intenta m치s tarde."
