main = """\
Â¡Bienvenido a la Taberna de la ciudad de Krezar!

AquÃ­ puedes relajarte, tomarte algo o resolver disputas retando a alguien a un duelo. \
TambiÃ©n puedes ganarte unas monedas participando en incursiones.

No dudes en pedir ayuda, estamos aquÃ­ pa' eso.
"""

raids = """\
Para participar en incursiones, debes aÃ±adir el bot a tu grupo.
Luego, en ciertos momentos del dÃ­a (<code>${settings_command}</code>), aparecerÃ¡n anuncios en la taberna \
con misiones que te pueden hacer ganar dinero. Si la incursiÃ³n tiene Ã©xito, Â¡la recompensa serÃ¡ mayor!

Â¡Y recuerda! Cuantos mÃ¡s Exploradores participen, mÃ¡s chances de ganar.

Cada vez que participas en una incursiÃ³n, tu ${energy_icon}EnergÃ­a disminuye y luego se recupera poco a poco."""

duels = """\
Si crees que alguien en la taberna estÃ¡ hablando por hablar, hay una arena especial detrÃ¡s para resolverlo.
Solo responde al mensaje del bocÃ³n con el comando ${duel_command}.

Pero ojo, pelear no es gratis. Alguien tiene que limpiar la sangre y recoger los dientes despuÃ©s.
"""

menu = """\
Como en toda taberna decente, aquÃ­ puedes comer y beber sabroso.

Mira el menÃº con ${menu_command} y pide lo que se te antoje.
TambiÃ©n puedes invitar a un amigo: responde a su mensaje \
o mencionalo en el pedido con <code>${order_command}1 @usuario</code>.

Y cuando termines... puedes lanzarle los platos a ese amigo molesto con ${throw_command}, \
o tirarlos a otro grupo con <code>${throw_to_group_command} TAG</code>.
"""

personage = """\
Entra a ${bot_username} para acceder al mostrador de registro.

AllÃ­ puedes cambiar tu nombre usando el cÃ­rculo mÃ¡gico.
O pagar por acceso al libro del olvido, para borrar tus habilidades y aprender unas nuevas.
"""

info = """\
Las noticias del proyecto estÃ¡n en este canal: ${news_channel_username}.

El cÃ³digo fuente del juego estÃ¡ <a href="${source_code_link}">aquÃ­</a>.
TambiÃ©n puedes usar ese enlace para ayudar con la traducciÃ³n del contenido.
"""

battleSystem = """\
CaracterÃ­sticas del personaje:
${health_icon}Salud ${attack_icon}Ataque ${defense_icon}Defensa
${strength_icon}Fuerza ${agility_icon}Agilidad ${wisdom_icon}SabidurÃ­a

Reglas del combate:
1. Si tu ${health_icon}Salud llega a 0, estÃ¡s muerto.
2. ${strength_icon}Fuerza vence a ${agility_icon}Agilidad.
3. ${agility_icon}Agilidad vence a ${wisdom_icon}SabidurÃ­a.
4. ${wisdom_icon}SabidurÃ­a vence a ${strength_icon}Fuerza.
5. ${strength_icon}Fuerza mejora los ${normal_attack_icon}ataques normales.
6. ${agility_icon}Agilidad mejora tu chance de ${dodge_icon}esquivar.
7. ${wisdom_icon}SabidurÃ­a mejora el daÃ±o ${crit_attack_icon}crÃ­tico.
8. ${attack_icon}Ataque sube todo el daÃ±o que haces.
9. ${defense_icon}Defensa reduce el daÃ±o recibido.
10. El combate es por turnos. Cada turno haces un ataque.
"""

seasons = """\
âš¡ Cada temporada comienza con una tormenta mÃ¡gica devastadora que arrasa con casi todo el oro \
y daÃ±a el equipo de los Exploradores.

ğŸ”¥ Â¡DespuÃ©s llega la nueva temporada! Todos los Exploradores activos del ciclo anterior reciben una insignia especial, \
y en las tabernas se publican los nombres de los mejores, para honrar sus hazaÃ±as.

ğŸ“£ Sigue las noticias y actualizaciones aquÃ­: ${news_channel_username}!
"""


raidsButton = "ğŸ—¡Incursiones"
duelsButton = "ğŸ¤ºDuelos"
menuButton = "ğŸ»Taberna"
personageButton = "ğŸ”°Explorador"
infoButton = "ğŸ’¬MÃ¡s"
battleSystemButton = "âš”ï¸Sistema de combate"
seasonsButton = "âš¡ï¸Temporadas"
