joinRaidEvent = "Unirse a la incursi贸n  ${energy_icon}${energy_cost}%"
raidStartsPrefix = "La batalla comienza en"
userAlreadyInThisRaid = "隆Ya est谩s participando en este incursi贸n!"
userAlreadyInOtherEvent = "隆Ya est谩s en otro evento!"
exhaustedAlert = "锔隆Est谩s molido! Puedes luchar, pero sin recompensa. No se gastar谩 energ铆a."
expiredRaid = "锔隆La incursi贸n ya termin贸!"
raidInProcess = "锔La incursi贸n ya empez贸"
successJoinRaid = "隆Te uniste a la incursi贸n con 茅xito!"
successRaid = [
    "隆Evento completado! La incursi贸n fue un 茅xito.",
    "隆Tremenda pelea! Lo lograron, aqu铆 est谩 su recompensa.",
    "隆Los enemigos cayeron! Resultaron no ser unos blandengues."
]
failureRaid = [
    "Los Exploradores fallaron La incursi贸n. 驴Pa' eso les pagamos?",
    "Ay, fallamos. Tal vez hace falta m谩s gente.",
    "La pelea no sali贸 bien. Ahora est谩n hasta el cuello de problemas."
]
zeroParticipants = [
    "Nadie acept贸 el encargo Esta vez no hay billete pa' nadie."
]
personageRaidResult = "${dead_icon_or_empty}${raid_participant}: ${damage_dealt}锔 ${damage_taken} +${money}${money_icon}"
raidResult = """Enemigos: ${remain_enemies_health}/${total_enemies_health}わ ${remain_enemies_count}/${total_enemies_count}

Mejores Exploradores:
${top_participants_list}${from_new_line_items_for_personages}

Informe dLa incursi贸n: ${raid_report_command}"""
successItemForPersonage = [
    "隆${personage_badge_with_name} encuentra un <code>${short_item}</code> en el campo! 隆Eso se celebra con una fr铆a en la taberna!"
]
notEnoughSpaceInBagForItem = [
    "${personage_badge_with_name} encuentra un <code>${short_item}</code>, pero la mochila est谩 llena..."
]
raidParticipants = "Participantes: ${raid_participants_list}"
raidParticipant = "${personage_badge_with_name}${exhausted_icon_or_empty}"
report = """Tu informe de la 煤ltima incursi贸n:
${personage_battle_report}"""
reportNotPresentForPersonage = "No encontramos tu informe dLa incursi贸n en los archivos"
lastGroupRaidReportNotFound = "No participaste en la 煤ltima incursi贸n"