worldRaidResearchEnd = """\
隆Se encontr贸 la incursi贸n mundial! Top de Exploradores por contribuci贸n:

${top_personage_list}"""
worldRaidBattle = """\
${world_raid_intro}

Enemigos: ${enemies_health}わ ${enemies_count}

Fondo: ${money_icon}${fund_value}

La batalla comienza en: ${duration}
Mientras tanto, puedes seguir participando en otros eventos.

${optional_participants}"""
endedWorldRaidBattle = """\
${world_raid_intro}

Enemigos: ${enemies_health}わ ${enemies_count}

Fondo: ${money_icon}${fund_value}

${optional_participants}
"""
worldRaidParticipants = """\
Grupos: ${group_tags}
Participantes: ${participants_count}"""
joinWorldRaidButton = "Unirse ${energy_icon}${energy_cost}%"
successJoin = "隆Ya est谩s participando en la incursi贸n mundial!"
alreadyInRaid = "隆Ya est谩s dentro!"
notEnoughEnergy = "隆No tienes suficiente energ铆a!"
mustBeInRegisteredGroup = "Tienes que pertenecer a un grupo registrado para participar en la incursi贸n mundial."
raidNotFound = "锔隆No se encontr贸 ninguna incursi贸n mundial activa!"
groupNotification = "隆La incursi贸n mundial comenzar谩 en <code>${duration}</code>! M谩s detalles aqu铆: ${channel}"
successBattle = """\
隆La incursi贸n mundial termin贸! Los enemigos fueron derrotados, 隆es hora de repartir el bot铆n!

${battle_result}

Bot铆n:
${legendary_icon} x ${legendary_count}
${epic_icon} x ${epic_count}

Puedes ver el resultado en tu perfil con <code>${raid_report_command}</code>"""
failedBattle = """\
隆La incursi贸n mundial termin贸! Los Exploradores fueron vencidos, pero a煤n queda chance pa'l desquite...

Enemigos restantes: ${enemies_health}わ ${enemies_count}

${battle_result}

Puedes ver el resultado en tu perfil con <code>${raid_report_command}</code>"""
battleResult = """\
Mejores grupos:
${group_results}

Mejores Exploradores:
${personage_results}"""

groupResult = "${group_tag_with_badage} ${participants_count} 锔${damage_dealt} ${damage_taken} +${money_icon}${money}"
personageResult = "${dead_icon_or_empty}${personage_badge_with_name} 锔${damage_dealt} ${damage_taken} +${money_icon}${money}"
personageWorldRaidReportNotFound = "No participaste en la 煤ltima incursi贸n mundial"
groupWorldRaidReportNotFound = "El grupo no particip贸 en la 煤ltima incursi贸n mundial"
personageWorldRaidReport = """\
Tu informe de la incursi贸n mundial:
${personage_battle_report}"""
